### ISSUE TITLE
Styling issue after adding a note

### ISSUE THREAD

**Issue by sevenseacat** [radar/twist-v2#10]
<img width="299" alt="Screen Shot 2020-03-03 at 5 11 20 pm" src="https://user-images.githubusercontent.com/543859/75760506-5a3fb180-5d72-11ea-9fbe-b22e41957f0c.png">

Looks like the `0 notes` part hasn't been removed and a `1 note` thing has dropped over the top. Tested in Firefox 73.0.1.

**Comment by radar** [comment]
Fixed by https://github.com/radar/twist-v2/commit/98b3a7c
