### ISSUE TITLE
Frontend app gives an error!

### ISSUE THREAD

**Issue by mechanicles** [radar/twist-v2#2]
I followed the required steps for backend and frontend apps but while starting the frontend app, I'm getting this error.

```
Failed to compile.

./src/index.js
Module not found: Can't resolve 'bootstrap/dist/css/bootstrap.css' in '/Users/santosh/my-free-work/twist-v2/frontend/src'
```

**Comment by radar** [comment]
Thanks for taking a look at the app!

That bootstrap code was leftover from an attempt last night to bring the bootstrap dependency in with a local package.

I've removed that line now in 1d8ce3b.

Thanks for letting me know about it!
