### ISSUE TITLE
Code rendering in a note not working.

### ISSUE THREAD

**Issue by TigerWolf** [radar/twist-v2#22]
For example:

```
[NOTE]
.Template inheritance
====
Notice how i
[source, ruby]
----
render "sidebar"
----
aa
```

Produces this:

<img width="1127" alt="Screen Shot 2020-04-15 at 2 20 49 pm" src="https://user-images.githubusercontent.com/501033/79300037-c2aeb080-7f24-11ea-938b-86a571918292.png">

**Comment by radar** [comment]
![](https://media1.tenor.com/images/614c9b4639a2588383f47e138177da81/tenor.gif?itemid=12014506)
